// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCelFKmPaaBUcaRA9Z-Lh85ePfd79Lv1K8',
    appId: '1:485243538959:web:d220089e364ef012b4dd7a',
    messagingSenderId: '485243538959',
    projectId: 'excelerate-pathfinder-661eb',
    authDomain: 'excelerate-pathfinder-661eb.firebaseapp.com',
    storageBucket: 'excelerate-pathfinder-661eb.firebasestorage.app',
    measurementId: 'G-KTGMHGZTGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqoak01d65Flt2NULf0dVIyZrYE4ryAB0',
    appId: '1:485243538959:android:4febdcda4ab2566fb4dd7a',
    messagingSenderId: '485243538959',
    projectId: 'excelerate-pathfinder-661eb',
    storageBucket: 'excelerate-pathfinder-661eb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCelFKmPaaBUcaRA9Z-Lh85ePfd79Lv1K8',
    appId: '1:485243538959:web:609f89701c8ce69fb4dd7a',
    messagingSenderId: '485243538959',
    projectId: 'excelerate-pathfinder-661eb',
    authDomain: 'excelerate-pathfinder-661eb.firebaseapp.com',
    storageBucket: 'excelerate-pathfinder-661eb.firebasestorage.app',
    measurementId: 'G-10FVMYMQHF',
  );
}
